title: "Ritik Agarwal"
description: "Smart contract security researcher and security engineer."
baseurl: "/SamBlogs"
theme: minima
show_excerpts: false

email: ritikagarwal570@gmail.com
github_username: Ritik-Agarwal50
twitter_username: RitikkAgarwalll
linkedin_username: ritik-agarwal-bb0934182

header_pages:
  - portfolio.md
  - timeline.md
  - cv.md
  - about.md
  - blog.md
